# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ExampPrep CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npx playwright install
    
    - name: Run Unit tests
      run: npm run test:unit

    - name: Start the app
      run: |
        npm start &
        echo $! > pid.txt
      env:
        CI: true

    - name: Wait for the app to be ready
      run: |
        sleep 5
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080

    - name: Run UI tests
      run: npm run test:ui

    - name: Stop the app
      run: kill $(cat pid.txt)

    - name: My Name
      run: echo "Hello, my name is!"
